import { User, Users, Building2 } from "lucide-react";
import { Plan } from "@/types";

export const plans: Plan[] = [
    {
      id: "standalone",
      name: "Edesio Solo",
      icon: User,
      monthlyPrice: 4.90,
      description: "Pour les apprenants individuels et autodidactes.",
      classes: 1,
      features: [
        { text: "1 classe incluse", highlight: true },
        { text: "Jusqu'à 50 cours", highlight: false },
        { text: "Génération de questions IA", highlight: false },
        { text: "Chatbot IA personnel", highlight: false },
        { text: "Suivi de progression", highlight: false },
        { text: "Application mobile", highlight: false },
      ],
      priceMonthlyId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_STANDALONE ?? "",
      priceAnnualId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_STANDALONE_ANNUAL ?? "",
      gradient: "from-yellow-50 to-amber-50",
      darkGradient: "dark:from-yellow-900/20 dark:to-amber-900/20",
      iconBg: "bg-gradient-to-br from-yellow-500 to-amber-600",
      accentColor: "text-yellow-600 dark:text-yellow-400",
      popular: false,
    },
    {
      id: "teacher",
      name: "Edesio Professeur",
      icon: Users,
      monthlyPrice: 24.90,
      description: "Pour un professeur avec plusieurs classes.",
      classes: 10,
      features: [
        { text: "10 classes incluses", highlight: true },
        { text: "Jusqu'à 50 cours par classe", highlight: false },
        { text: "Élèves illimités", highlight: false },
        { text: "Statistiques détaillées", highlight: false },
        { text: "Application mobile", highlight: false },
      ],
      priceMonthlyId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_TEACHER ?? "",
      priceAnnualId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_TEACHER_ANNUAL ?? "",
      gradient: "from-indigo-50 to-purple-50",
      darkGradient: "dark:from-indigo-900/20 dark:to-purple-900/20",
      iconBg: "bg-gradient-to-br from-indigo-500 to-purple-600",
      accentColor: "text-indigo-600 dark:text-indigo-400",
      popular: false,
    },
    {
      id: "establishment",
      name: "Edesio Établissement",
      icon: Building2,
      monthlyPrice: 299.90,
      description: "Couvrez l'ensemble de votre établissement.",
      classes: 150,
      features: [
        { text: "150 classes incluses", highlight: true },
        { text: "Jusqu'à 50 cours par classe", highlight: false },
        { text: "Professeurs illimités", highlight: false },
        { text: "Élèves illimités", highlight: false },
        { text: "Support prioritaire", highlight: false },
        { text: "Statistiques établissement", highlight: false },
        { text: "Application mobile", highlight: false },
      ],
      priceMonthlyId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_ESTABLISHMENT ?? "",
      priceAnnualId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_ESTABLISHMENT_ANNUAL ?? "",
      gradient: "from-emerald-50 to-green-50",
      darkGradient: "dark:from-emerald-900/20 dark:to-green-900/20",
      iconBg: "bg-gradient-to-br from-emerald-500 to-green-600",
      accentColor: "text-emerald-600 dark:text-emerald-400",
      popular: true,
    },
  ];

export const annualDiscountPercent = 15;